name: promosave_empresa
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.1.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  brasil_fields: ^1.4.4
  smooth_star_rating_nsafe: ^1.0.0+1
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.3+1
  google_place: ^0.4.7
  auto_size_text: ^3.0.0
  url_launcher: ^6.0.15
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf